### PR TITLE
overly-excited replacing alpha-stacker

### PR DESCRIPTION
**Pull request by katerebekah**
Changed alpha stacker to similar exercise called overly excited. Added additional challenge at the end. We could call this shatner-speak instead of overly-excited, if we want to be funny.

### CODE REVIEW

**Comment by stevebrownlee** [comment]
👍

**Comment by katerebekah** [comment]
@stevebrownlee overly-excited vs shatner-speak?

**Comment by stevebrownlee** [comment]
@katerebekah ship as is with excite speak

**Comment by megducharme** [comment]
This is awesome!

**Pull request merged**
