### PR TITLE
updated gif path on tree exercise

### PR DESCRIPTION
**Pull request by megducharme**
I am not sure what was wrong with the current path, but this one should work.

### CODE REVIEW

**Comment by megducharme** [comment]
The problem was in the forked D18 version.

**Comment by stevebrownlee** [comment]
@brendalong Since this PR is trying to merge from `master`, I'll let you approve to make sure you want those changes in your branch right now.

**Comment by brendalong** [comment]
I placed the orchard image inside prototype exercise folder giving it a more direct path.

**Comment by stevebrownlee** [comment]
👍

**Comment by brendalong** [comment]
fixed in the merge to master

**Pull request closed without merging**
